#include "applicabilitywidget.h"
#include <QFileDialog>
#include <QHeaderView>
#include <QMessageBox>
#include <QSqlDatabase>
#include <QSqlQuery>
#include <QtWidgets>

namespace {
void fill(QComboBox*c,QSqlDatabase db,const QString&sql,const QString&all){c->blockSignals(true);c->clear();c->addItem(all,-1);QSqlQuery q(sql,db);while(q.next())c->addItem(q.value(1).toString(),q.value(0));c->blockSignals(false);}
}
ApplicabilityWidget::ApplicabilityWidget(QWidget *parent):QWidget(parent){
  auto tabs=new QTabWidget;
  auto configPage=new QWidget;auto cv=new QVBoxLayout(configPage);auto ca=new QHBoxLayout;
  auto add=new QPushButton("Nouvelle");auto edit=new QPushButton("Modifier");m_archive=new QPushButton("Archiver / restaurer");ca->addWidget(add);ca->addWidget(edit);ca->addWidget(m_archive);ca->addStretch();
  m_configurations=new QTableWidget(0,7);m_configurations->setHorizontalHeaderLabels({"Code","Libellé","Description","Ordre","État","Utilisations","Mise à jour"});m_configurations->setSelectionBehavior(QAbstractItemView::SelectRows);m_configurations->setEditTriggers(QAbstractItemView::NoEditTriggers);m_configurations->horizontalHeader()->setStretchLastSection(true);
  m_history=new QTableWidget(0,4);m_history->setHorizontalHeaderLabels({"Date","Événement","Avant","Après"});m_history->setEditTriggers(QAbstractItemView::NoEditTriggers);m_history->horizontalHeader()->setStretchLastSection(true);
  cv->addLayout(ca);cv->addWidget(m_configurations,2);cv->addWidget(new QLabel("Historique de la configuration sélectionnée"));cv->addWidget(m_history,1);tabs->addTab(configPage,"Configurations");
  auto matrixPage=new QWidget;auto mv=new QVBoxLayout(matrixPage);auto filters=new QHBoxLayout;m_pt=new QComboBox;m_document=new QComboBox;m_status=new QComboBox;m_type=new QComboBox;m_obsolete=new QCheckBox("Inclure les exigences obsolètes");m_archivedConfigurations=new QCheckBox("Afficher les configurations archivées");for(auto p:QList<QPair<QString,QWidget*>>{{"Branche PT",m_pt},{"Document",m_document},{"Statut",m_status},{"Type",m_type}}){filters->addWidget(new QLabel(p.first));filters->addWidget(p.second);}filters->addWidget(m_obsolete);filters->addWidget(m_archivedConfigurations);filters->addStretch();auto exportButton=new QPushButton("Exporter XLSX…");filters->addWidget(exportButton);
  m_rate=new QLabel;m_rate->setTextInteractionFlags(Qt::TextSelectableByMouse);m_matrix=new QTableWidget;m_matrix->setSelectionBehavior(QAbstractItemView::SelectRows);m_matrix->setSelectionMode(QAbstractItemView::SingleSelection);m_matrix->setEditTriggers(QAbstractItemView::NoEditTriggers);m_matrix->horizontalHeader()->setSectionResizeMode(QHeaderView::ResizeToContents);m_matrix->verticalHeader()->hide();mv->addLayout(filters);mv->addWidget(m_rate);mv->addWidget(m_matrix);tabs->addTab(matrixPage,"Matrice exigences × configurations");auto root=new QVBoxLayout(this);root->addWidget(tabs);
  m_rate->setTextFormat(Qt::RichText);m_rate->setTextInteractionFlags(Qt::TextBrowserInteraction);m_rate->setOpenExternalLinks(false);
  connect(m_rate,&QLabel::linkActivated,this,[this]{m_matrix->setFocus();m_matrix->scrollToTop();});
  connect(add,&QPushButton::clicked,this,[this]{editConfiguration();});connect(edit,&QPushButton::clicked,this,[this]{int r=m_configurations->currentRow();if(r>=0)editConfiguration(m_configurations->item(r,0)->data(Qt::UserRole).toInt());});connect(m_configurations,&QTableWidget::cellDoubleClicked,this,[this](int r){editConfiguration(m_configurations->item(r,0)->data(Qt::UserRole).toInt());});
  connect(m_archive,&QPushButton::clicked,this,[this]{int r=m_configurations->currentRow();if(r<0)return;const auto c=m_service.configuration(m_configurations->item(r,0)->data(Qt::UserRole).toInt());const auto result=m_service.setConfigurationActive(c.id,!c.active);if(!result.success)QMessageBox::warning(this,"Configuration",result.message);else{refresh();emit dataChanged();}});
  connect(m_configurations,&QTableWidget::itemSelectionChanged,this,[this]{m_history->setRowCount(0);int r=m_configurations->currentRow();if(r<0)return;QSqlQuery q(QSqlDatabase::database(m_connection));q.prepare("SELECT EVENT_TIME,EVENT_TYPE,COALESCE(BEFORE_JSON,''),COALESCE(AFTER_JSON,'') FROM EVENT_LOG WHERE OBJECT_TYPE='CONFIGURATION' AND OBJECT_ID=? ORDER BY ID DESC");q.addBindValue(m_configurations->item(r,0)->data(Qt::UserRole));if(q.exec())while(q.next()){int row=m_history->rowCount();m_history->insertRow(row);for(int c=0;c<4;++c)m_history->setItem(row,c,new QTableWidgetItem(q.value(c).toString()));}});
  for(auto*c:{m_pt,m_document,m_status,m_type})
    connect(c,QOverload<int>::of(&QComboBox::currentIndexChanged),this,&ApplicabilityWidget::refreshMatrix);
  connect(m_obsolete,&QCheckBox::toggled,this,&ApplicabilityWidget::refreshMatrix);
  connect(m_archivedConfigurations,&QCheckBox::toggled,this,&ApplicabilityWidget::refreshMatrix);
  connect(m_matrix,&QTableWidget::cellDoubleClicked,this,[this](int row,int){
    if(row>=0&&row<m_rows.size())emit openRequirementRequested(m_rows[row].requirementId);
  });
  connect(exportButton,&QPushButton::clicked,this,[this]{QString path=QFileDialog::getSaveFileName(this,"Exporter la matrice","matrice-applicabilite.xlsx","Classeur Excel (*.xlsx)");if(path.isEmpty())return;if(!path.endsWith(".xlsx",Qt::CaseInsensitive))path+=".xlsx";ApplicabilityFilter f;f.ptRootId=m_pt->currentData().toInt();f.documentId=m_document->currentData().toInt();f.statusId=m_status->currentData().toInt();f.typeId=m_type->currentData().toInt();f.includeObsoleteRequirements=m_obsolete->isChecked();f.includeArchivedConfigurations=m_archivedConfigurations->isChecked();const auto r=m_service.exportXlsx(path,f);if(!r.success)QMessageBox::warning(this,"Export XLSX",r.message);else QMessageBox::information(this,"Export XLSX",r.message);});
}
void ApplicabilityWidget::setConnectionName(const QString&name){m_connection=name;m_service.setConnectionName(name);refresh();}
void ApplicabilityWidget::refresh(){QSqlDatabase db=QSqlDatabase::database(m_connection,false);if(m_connection.isEmpty()||!db.isValid()||!db.isOpen()){m_configurations->setRowCount(0);m_matrix->setRowCount(0);return;}fill(m_pt,db,"SELECT ID,NAME FROM PT WHERE ARCHIVED=0 ORDER BY POSITION,NAME","Toutes les branches");fill(m_document,db,"SELECT ID,COALESCE(NULLIF(REFERENCE,''),TITLE) FROM DOCUMENT ORDER BY TITLE","Tous les documents");fill(m_status,db,"SELECT ID,STATUS FROM REQ_STATUS ORDER BY ID","Tous les statuts");fill(m_type,db,"SELECT ID,TYPE FROM REQ_TYPE ORDER BY TYPE","Tous les types");refreshConfigurations();refreshMatrix();}
void ApplicabilityWidget::refreshConfigurations(){QString error;m_configurationRecords=m_service.configurations(true,&error);m_configurations->setRowCount(m_configurationRecords.size());for(int r=0;r<m_configurationRecords.size();++r){const auto&c=m_configurationRecords[r];QStringList values{c.code,c.label,c.description,QString::number(c.position),c.active?"Active":"Archivée",QString::number(c.useCount),c.updatedAt};for(int col=0;col<values.size();++col)m_configurations->setItem(r,col,new QTableWidgetItem(values[col]));m_configurations->item(r,0)->setData(Qt::UserRole,c.id);if(!c.active)for(int col=0;col<values.size();++col)m_configurations->item(r,col)->setForeground(Qt::gray);}}
void ApplicabilityWidget::editConfiguration(int id){ConfigurationRecord c=id<0?ConfigurationRecord():m_service.configuration(id);QDialog d(this);d.setWindowTitle(id<0?"Nouvelle configuration":"Modifier la configuration");auto form=new QFormLayout(&d);QLineEdit code(c.code),label(c.label);QTextEdit description;description.setPlainText(c.description);QSpinBox position;position.setRange(0,999999);position.setValue(c.position);QCheckBox active("Active");active.setChecked(c.active);form->addRow("Code unique",&code);form->addRow("Libellé",&label);form->addRow("Description",&description);form->addRow("Ordre",&position);form->addRow("État",&active);QDialogButtonBox buttons(QDialogButtonBox::Save|QDialogButtonBox::Cancel);if(id>=0){auto changes=buttons.addButton("Changements liés",QDialogButtonBox::ActionRole);connect(changes,&QPushButton::clicked,&d,[this,id]{emit openChangesRequested(id);});}form->addRow(&buttons);connect(&buttons,&QDialogButtonBox::accepted,&d,&QDialog::accept);connect(&buttons,&QDialogButtonBox::rejected,&d,&QDialog::reject);if(d.exec()!=QDialog::Accepted)return;c.code=code.text();c.label=label.text();c.description=description.toPlainText();c.position=position.value();c.active=active.isChecked();auto result=m_service.saveConfiguration(c);if(!result.success)QMessageBox::warning(this,"Configuration",result.message);else{refresh();emit dataChanged();}}
void ApplicabilityWidget::refreshMatrix(){if(m_connection.isEmpty())return;ApplicabilityFilter f;f.ptRootId=m_pt->currentData().toInt();f.documentId=m_document->currentData().toInt();f.statusId=m_status->currentData().toInt();f.typeId=m_type->currentData().toInt();f.includeObsoleteRequirements=m_obsolete->isChecked();f.includeArchivedConfigurations=m_archivedConfigurations->isChecked();QString error;m_rows=m_service.matrix(f,&error);m_configurationRecords=m_service.configurations(f.includeArchivedConfigurations);m_matrix->setUpdatesEnabled(false);m_matrix->setSortingEnabled(false);m_matrix->setColumnCount(6+m_configurationRecords.size());QStringList headers{"Code","Titre","Statut","Type","Product Trees","Documents"};for(const auto&c:m_configurationRecords)headers<<c.code+(c.active?QString():" [archivée]");m_matrix->setHorizontalHeaderLabels(headers);for(int c=0;c<m_matrix->columnCount();++c){auto*header=m_matrix->horizontalHeaderItem(c);if(header){header->setBackground(QBrush());header->setForeground(QBrush());}}m_matrix->setRowCount(m_rows.size());for(int r=0;r<m_rows.size();++r){const auto&row=m_rows[r];QStringList base{row.code,row.title,row.status,row.type,row.productTrees,row.document};for(int c=0;c<base.size();++c)m_matrix->setItem(r,c,new QTableWidgetItem(base[c]));for(int c=0;c<row.cells.size();++c){const auto&cell=row.cells[c];auto item=new QTableWidgetItem(cell.applicable?"✓":"—");item->setTextAlignment(Qt::AlignCenter);item->setToolTip((cell.explicitValue?(cell.sourcePtId<0?"Valeur simple":"Exception PT")+(cell.comment.isEmpty()?QString():" — "+cell.comment):"Non renseigné")+"\nDouble-cliquer pour ouvrir l'exigence.");if(!m_configurationRecords[c].active){item->setBackground(QColor("#e4e4e4"));item->setForeground(Qt::darkGray);}else if(cell.sourcePtId>=0)item->setBackground(QColor("#fff2cc"));m_matrix->setItem(r,c+6,item);}}for(int c=0;c<m_configurationRecords.size();++c)if(!m_configurationRecords[c].active){auto*header=m_matrix->horizontalHeaderItem(c+6);if(header){header->setBackground(QColor("#d0d0d0"));header->setForeground(Qt::darkGray);}}m_matrix->setUpdatesEnabled(true);m_matrix->viewport()->update();m_rate->setText(QString("<a href=\"details\">Taux d'applicabilité : %1 %</a> — %2 exigences × %3 configurations. Double-cliquer une ligne pour ouvrir l'exigence.").arg(m_service.rate(m_rows),0,'f',2).arg(m_rows.size()).arg(m_configurationRecords.size()));}
