#include "coveragedashboard.h"
#include <QDateTime>
#include <QPainter>
#include <QSqlDatabase>
#include <QSqlQuery>
#include <QtWidgets>
#include <functional>

namespace {
const QColor Blue("#2878c8"),Green("#2e9d67"),Orange("#e59a2f"),Red("#d6534d"),Grey("#98a2ae"),Ink("#12345b");
QColor colorAt(int i){static const QList<QColor> c{
  QColor("#8b98a7"), // gris ardoise
  QColor("#e59a2f"), // orange
  QColor("#2e9d67"), // vert
  QColor("#d6534d"), // rouge
  QColor("#54a9b5"), // turquoise
  QColor("#2878c8"), // bleu
  QColor("#725bb5"), // violet
  QColor("#c45a91"), // rose
  QColor("#8a6a3f"), // brun
  QColor("#49a078"), // vert sauge
  QColor("#d47725"), // orange sombre
  QColor("#536d9f")  // bleu acier
};return c[i%c.size()];}
class Donut:public QWidget{
public: Donut(QString t,int v,int n,QColor c,std::function<void()> a,QWidget*p=nullptr):QWidget(p),title(std::move(t)),value(v),total(n),color(c),action(std::move(a)){setMinimumSize(135,145);setCursor(Qt::PointingHandCursor);setToolTip("Afficher les éléments manquants");}
protected:void paintEvent(QPaintEvent*)override{QPainter p(this);p.setRenderHint(QPainter::Antialiasing);int side=qMin(width()-24,96),x=(width()-side)/2;QRectF r(x,8,side,side);QPen pen(QColor("#dce5ee"),11);p.setPen(pen);p.drawArc(r,0,360*16);int pct=total?qRound(100.0*value/total):0;pen.setColor(color);p.setPen(pen);p.drawArc(r,90*16,-pct*360*16/100);p.setPen(Ink);QFont f=p.font();f.setBold(true);f.setPointSize(13);p.setFont(f);p.drawText(QRectF(x,31,side,28),Qt::AlignCenter,QString::number(pct)+" %");f.setBold(false);f.setPointSize(9);p.setFont(f);p.drawText(QRectF(x,57,side,20),Qt::AlignCenter,QString("%1 / %2").arg(value).arg(total));f.setPointSize(10);p.setFont(f);p.drawText(QRectF(3,111,width()-6,32),Qt::AlignHCenter|Qt::AlignTop|Qt::TextWordWrap,title);}
void mouseReleaseEvent(QMouseEvent*)override{if(action)action();}
private:QString title;int value,total;QColor color;std::function<void()> action;};
class Bars:public QWidget{
public:Bars(QList<CoverageSlice> r,bool s,QWidget*p=nullptr):QWidget(p),rows(std::move(r)),stacked(s){setMinimumHeight(stacked?102:qMax(120,rows.size()*31+12));}
protected:void paintEvent(QPaintEvent*)override{QPainter p(this);p.setRenderHint(QPainter::Antialiasing);int maximum=1,total=0;for(const auto&r:rows){maximum=qMax(maximum,r.value);total+=r.value;}if(stacked){int x=8,y=12,w=width()-16,h=34,used=0;for(int i=0;i<rows.size();++i){auto&r=rows[i];int part=i==rows.size()-1?w-used:qRound(double(w)*r.value/qMax(1,total));p.fillRect(QRect(x+used,y,part,h),colorAt(i));if(part>28){p.setPen(Qt::white);p.drawText(QRect(x+used,y,part,h),Qt::AlignCenter,QString::number(r.value));}used+=part;}int lx=8,ly=62;for(int i=0;i<rows.size();++i){p.setBrush(colorAt(i));p.setPen(Qt::NoPen);p.drawEllipse(lx,ly,10,10);p.setPen(Ink);p.drawText(QRect(lx+15,ly-3,125,18),Qt::AlignLeft|Qt::AlignVCenter,rows[i].label);lx+=140;if(lx+125>width()){lx=8;ly+=20;}}}else for(int i=0;i<rows.size();++i){int y=8+i*31;p.setPen(Ink);p.drawText(QRect(4,y,185,22),Qt::AlignLeft|Qt::AlignVCenter,rows[i].label);int bw=qRound((width()-240.0)*rows[i].value/maximum);p.fillRect(190,y+2,qMax(2,bw),17,colorAt(i+1));p.setPen(Ink);p.drawText(QRect(200+bw,y,38,22),Qt::AlignLeft|Qt::AlignVCenter,QString::number(rows[i].value));}}
private:QList<CoverageSlice> rows;bool stacked;};
QFrame*panel(const QString&t){auto*f=new QFrame;f->setObjectName("dashboardPanel");auto*l=new QVBoxLayout(f);l->setContentsMargins(16,12,16,12);auto*h=new QLabel(t);h->setObjectName("sectionTitle");l->addWidget(h);return f;}
QVBoxLayout*body(QFrame*p){return qobject_cast<QVBoxLayout*>(p->layout());}
QLabel*kpi(const QString&n,const QString&l,const QColor&c){auto*w=new QLabel(QString("<span style='font-size:25px;font-weight:700;color:%1'>%2</span><br><span style='color:#29496c'>%3</span>").arg(c.name(),n,l));w->setObjectName("kpi");w->setMinimumHeight(78);w->setAlignment(Qt::AlignCenter);return w;}
void fill(QComboBox*c,const QSqlDatabase&db,const QString&q,const QString&a){c->blockSignals(true);c->clear();c->addItem(a,-1);QSqlQuery x(q,db);while(x.next())c->addItem(x.value(1).toString(),x.value(0));c->blockSignals(false);}
CoverageMetric findMetric(const QList<CoverageMetric>&ms,const QString&key){for(const auto&m:ms)if(m.key==key)return m;return {};}
void clearLayout(QLayout *layout){
  while(auto *item=layout->takeAt(0)){
    if(auto *childLayout=item->layout()){
      clearLayout(childLayout);
    }
    if(auto *widget=item->widget())delete widget;
    delete item;
  }
}
}

CoverageDashboard::CoverageDashboard(QWidget*parent):QWidget(parent){auto*root=new QVBoxLayout(this);root->setContentsMargins(12,8,12,8);auto*head=new QHBoxLayout;auto*titles=new QVBoxLayout;auto*title=new QLabel("Tableau de bord du projet");title->setObjectName("dashboardTitle");m_state=new QLabel("Aucun projet ouvert.");m_state->setObjectName("dashboardState");titles->addWidget(title);titles->addWidget(m_state);head->addLayout(titles);head->addStretch();auto*reload=new QPushButton("Actualiser");head->addWidget(reload);root->addLayout(head);auto*filters=new QHBoxLayout;m_pt=new QComboBox;m_document=new QComboBox;m_configuration=new QComboBox;m_status=new QComboBox;m_type=new QComboBox;m_search=new QLineEdit;m_search->setPlaceholderText("Rechercher…");m_obsolete=new QCheckBox("Inclure les obsolètes");for(auto p:QList<QPair<QString,QComboBox*>>{{"Product Tree",m_pt},{"Document",m_document},{"Configuration",m_configuration},{"Statut",m_status},{"Type",m_type}}){filters->addWidget(new QLabel(p.first+" :"));filters->addWidget(p.second);}filters->addWidget(m_search,1);filters->addWidget(m_obsolete);root->addLayout(filters);auto*host=new QWidget;m_content=new QVBoxLayout(host);m_content->setContentsMargins(0,5,0,0);auto*scroll=new QScrollArea;scroll->setWidgetResizable(true);scroll->setFrameShape(QFrame::NoFrame);scroll->setWidget(host);root->addWidget(scroll,1);setStyleSheet("#dashboardTitle{font-size:24px;font-weight:700;color:#12345b}#dashboardState{color:#687b91}#sectionTitle{font-size:18px;font-weight:700;color:#0862ad}#dashboardPanel,#kpi{background:white;border:1px solid #d5e0ea;border-radius:7px}QComboBox,QLineEdit{min-height:25px}QScrollArea{background:#f3f7fa}");connect(reload,&QPushButton::clicked,this,&CoverageDashboard::refresh);for(auto*c:{m_pt,m_document,m_configuration,m_status,m_type})connect(c,QOverload<int>::of(&QComboBox::currentIndexChanged),this,&CoverageDashboard::refresh);connect(m_search,&QLineEdit::returnPressed,this,&CoverageDashboard::refresh);connect(m_obsolete,&QCheckBox::toggled,this,&CoverageDashboard::refresh);}
void CoverageDashboard::setConnectionName(const QString&n){m_connection=n;m_service.setConnectionName(n);loadFilters();refresh();}
void CoverageDashboard::loadFilters(){auto db=QSqlDatabase::database(m_connection,false);if(!db.isValid()||!db.isOpen())return;fill(m_pt,db,"SELECT ID,NAME FROM PT WHERE COALESCE(ARCHIVED,0)=0 ORDER BY POSITION,NAME","Tous");fill(m_document,db,"SELECT ID,COALESCE(NULLIF(REFERENCE,''),TITLE) FROM DOCUMENT ORDER BY TITLE","Tous");fill(m_configuration,db,"SELECT ID,CODE FROM CONFIGURATION WHERE ACTIVE=1 ORDER BY POSITION,CODE","Toutes");fill(m_status,db,"SELECT ID,STATUS FROM REQ_STATUS ORDER BY ID","Tous");fill(m_type,db,"SELECT ID,TYPE FROM REQ_TYPE ORDER BY TYPE","Tous");}
void CoverageDashboard::clearContent(){clearLayout(m_content);}
CoverageScope CoverageDashboard::scope()const{CoverageScope s;s.ptId=m_pt->currentData().toInt();s.documentId=m_document->currentData().toInt();s.configurationId=m_configuration->currentData().toInt();s.typeId=m_type->currentData().toInt();if(m_status->currentData().toInt()>=0)s.statusIds<<m_status->currentData().toInt();s.search=m_search->text();s.includeObsolete=m_obsolete->isChecked();return s;}
void CoverageDashboard::refresh(){clearContent();QString error;auto s=m_service.snapshot(scope(),&error);if(!error.isEmpty()){m_state->setText(error);emit statusMessage(error);return;}m_state->setText(QString("%1 exigence(s) dans le périmètre — actualisé %2").arg(s.requirements).arg(QDateTime::currentDateTime().toString("dd/MM/yyyy HH:mm")));auto*kpis=new QHBoxLayout;int avg=0,n=0;for(auto key:{"allocation","traceability","documentation","verification","applicability"}){auto m=findMetric(s.metrics,key);if(m.total){avg+=m.percent();++n;}}kpis->addWidget(kpi(QString::number(s.requirements),"Exigences",Blue));kpis->addWidget(kpi(QString::number(n?avg/n:0)+" %","Couverture moyenne",Green));kpis->addWidget(kpi(QString::number(s.openChanges),"Changements non finalisés",Orange));kpis->addWidget(kpi(QString::number(s.documents),"Documents",Blue));kpis->addWidget(kpi(QString::number(s.activeConfigurations),"Configurations actives",Grey));m_content->addLayout(kpis);
auto*req=panel("Exigences");auto*rr=new QHBoxLayout;auto*sb=new QVBoxLayout;sb->addWidget(new QLabel("Répartition par statut"));sb->addWidget(new Bars(s.requirementStatuses,true));rr->addLayout(sb,5);auto*rings=new QHBoxLayout;for(auto key:{"allocation","traceability","documentation","verification","applicability"}){auto m=findMetric(s.metrics,key);rings->addWidget(new Donut(m.label,m.covered,m.total,Green,[this,m]{emit navigateRequested(m.page,m.missingFilter);}));}rr->addLayout(rings,7);body(req)->addLayout(rr);m_content->addWidget(req);
auto*mid=new QHBoxLayout;auto*changes=panel("Changements");auto*cr=new QHBoxLayout;auto*ct=new QVBoxLayout;ct->addWidget(new QLabel(QString("Par type (%1 changements)").arg(s.changes)));ct->addWidget(new Bars(s.changeTypes,false));cr->addLayout(ct,1);auto*cs=new QVBoxLayout;cs->addWidget(new QLabel("Par statut"));cs->addWidget(new Bars(s.changeStatuses,false));auto*pending=new QLabel(QString("%1 non finalisé(s)").arg(s.openChanges));pending->setStyleSheet("background:#fff4e5;color:#d66b00;padding:8px;font-weight:700;border:1px solid #efbd78;border-radius:4px");cs->addWidget(pending);cr->addLayout(cs,1);body(changes)->addLayout(cr);mid->addWidget(changes,1);auto*docs=panel("Documents");auto*dr=new QHBoxLayout;dr->addWidget(kpi(QString::number(s.documents),"documents",Blue));auto*dt=new QVBoxLayout;dt->addWidget(new QLabel("Par type"));dt->addWidget(new Bars(s.documentTypes,false));dr->addLayout(dt,1);body(docs)->addLayout(dr);auto*ds=new QHBoxLayout;ds->addWidget(kpi(QString::number(s.recentPublications),"publications sur 30 jours",Blue));ds->addWidget(kpi(QString::number(s.neverPublishedDocuments),"jamais publiés",Orange));body(docs)->addLayout(ds);mid->addWidget(docs,1);m_content->addLayout(mid);
auto*apps=panel("Applicabilité par configuration");if(s.configurations.isEmpty())body(apps)->addWidget(new QLabel("Aucune configuration définie."));for(const auto&c:s.configurations){auto*r=new QHBoxLayout;r->addWidget(new QLabel(c.code+" — "+c.label),2);auto*b=new QProgressBar;b->setRange(0,100);b->setValue(c.percent());b->setFormat(QString("%1 / %2 — %3 %").arg(c.applicable).arg(c.total).arg(c.percent()));b->setStyleSheet(QString("QProgressBar{border:0;background:#e5ebf1;height:19px;text-align:center}QProgressBar::chunk{background:%1}").arg(c.percent()>=80?Green.name():c.percent()>=60?Orange.name():Red.name()));r->addWidget(b,7);auto*a=new QLabel(c.active?"Active":"Archivée");a->setAlignment(Qt::AlignCenter);a->setStyleSheet(QString("color:white;background:%1;padding:3px;border-radius:4px").arg(c.active?Green.name():Grey.name()));r->addWidget(a);body(apps)->addLayout(r);}m_content->addWidget(apps);auto*hint=new QLabel("ⓘ Cliquez sur un indicateur de couverture pour ouvrir la liste filtrée.");hint->setStyleSheet("color:#476887;padding:6px");m_content->addWidget(hint);m_content->addStretch();}
