#include "producttreeservice.h"
#include <QSqlDatabase>
#include <QSqlError>
#include <QSqlQuery>

ProductTreeService::ProductTreeService(QString name):m_connectionName(name){}
void ProductTreeService::setConnectionName(const QString &name){m_connectionName=name;}
ProductTreeResult ProductTreeService::fail(const QString &m)const{return {false,m,{},{}};}
QString ProductTreeService::fullCode(int id)const{
 QSqlQuery q(QSqlDatabase::database(m_connectionName));q.prepare("WITH RECURSIVE P(ID,SEGMENT,PARENT,LVL) AS (SELECT ID,SEGMENT,PARENT,0 FROM PT WHERE ID=? UNION ALL SELECT X.ID,X.SEGMENT,X.PARENT,P.LVL+1 FROM PT X JOIN P ON X.ID=P.PARENT) SELECT SEGMENT FROM P ORDER BY LVL DESC");q.addBindValue(id);q.exec();QStringList p;while(q.next())p<<q.value(0).toString();QSqlQuery s("SELECT VALUE FROM PROJECT_META WHERE KEY='pt_separator'",QSqlDatabase::database(m_connectionName));s.next();return p.join(s.value(0).toString().isEmpty()?"-":s.value(0).toString());}
QStringList ProductTreeService::subtreeCodes(int id)const{QSqlQuery q(QSqlDatabase::database(m_connectionName));q.prepare("WITH RECURSIVE D(ID) AS(SELECT ? UNION ALL SELECT PT.ID FROM PT JOIN D ON PT.PARENT=D.ID) SELECT ID FROM D");q.addBindValue(id);q.exec();QStringList r;while(q.next())r<<fullCode(q.value(0).toInt());return r;}
ProductTreeResult ProductTreeService::addNode(int parentId,const QString &segment){QSqlDatabase db=QSqlDatabase::database(m_connectionName);if(segment.trimmed().isEmpty())return fail("Le segment est obligatoire.");QSqlQuery roots("SELECT COUNT(*) FROM PT WHERE PARENT IS NULL AND ARCHIVED=0",db);roots.next();if(parentId<0&&roots.value(0).toInt())return fail("Le projet possède déjà une racine.");QSqlQuery q(db);q.prepare("INSERT INTO PT(NAME,PARENT,SEGMENT,POSITION,CREATED_AT,UPDATED_AT) VALUES(?,?,?,COALESCE((SELECT MAX(POSITION)+1 FROM PT WHERE PARENT IS ?),0),CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)");q.addBindValue(parentId<0?segment.trimmed():fullCode(parentId)+"-"+segment.trimmed());q.addBindValue(parentId<0?QVariant():QVariant(parentId));q.addBindValue(segment.trimmed());q.addBindValue(parentId<0?QVariant():QVariant(parentId));if(!q.exec())return fail(q.lastError().text());return {true,"Élément ajouté.",{fullCode(q.lastInsertId().toInt())},{}};}
ProductTreeResult ProductTreeService::updateNode(int id,const QString &segment,const QString &description){QSqlDatabase db=QSqlDatabase::database(m_connectionName);QSqlQuery parent(db);parent.prepare("SELECT PARENT FROM PT WHERE ID=?");parent.addBindValue(id);parent.exec();parent.next();const int parentId=parent.value(0).isNull()?-1:parent.value(0).toInt();const QString name=parentId<0?segment.trimmed():fullCode(parentId)+"-"+segment.trimmed();QSqlQuery q(db);q.prepare("UPDATE PT SET SEGMENT=?,NAME=?,DESCRIPTION=?,UPDATED_AT=CURRENT_TIMESTAMP WHERE ID=?");q.addBindValue(segment.trimmed());q.addBindValue(name);q.addBindValue(description);q.addBindValue(id);if(segment.trimmed().isEmpty()||!q.exec())return fail(segment.trimmed().isEmpty()?"Le segment est obligatoire.":q.lastError().text());return {true,"Élément modifié.",{fullCode(id)},{}};}
ProductTreeResult ProductTreeService::moveNode(int id,int parentId,int position){QSqlDatabase db=QSqlDatabase::database(m_connectionName);QSqlQuery cycle(db);cycle.prepare("WITH RECURSIVE D(ID) AS(SELECT ? UNION ALL SELECT PT.ID FROM PT JOIN D ON PT.PARENT=D.ID) SELECT 1 FROM D WHERE ID=?");cycle.addBindValue(id);cycle.addBindValue(parentId);if(cycle.exec()&&cycle.next())return fail("Déplacement impossible : cycle détecté.");if(!db.transaction())return fail(db.lastError().text());QSqlQuery q(db);q.prepare("UPDATE PT SET PARENT=?,POSITION=?,UPDATED_AT=CURRENT_TIMESTAMP WHERE ID=?");q.addBindValue(parentId);q.addBindValue(position);q.addBindValue(id);if(!q.exec()){db.rollback();return fail(q.lastError().text());}QSqlQuery log(db);log.prepare("INSERT INTO EVENT_LOG(EVENT_TYPE,OBJECT_TYPE,OBJECT_ID,COMMENT) VALUES('MOVE','PT',?,'Déplacement de branche')");log.addBindValue(id);log.exec();if(!db.commit())return fail(db.lastError().text());return {true,"Branche déplacée.",subtreeCodes(id),{}};}
ProductTreeResult ProductTreeService::setArchived(int id,bool archived){QSqlQuery q(QSqlDatabase::database(m_connectionName));q.prepare("WITH RECURSIVE D(ID) AS(SELECT ? UNION ALL SELECT PT.ID FROM PT JOIN D ON PT.PARENT=D.ID) UPDATE PT SET ARCHIVED=?,UPDATED_AT=CURRENT_TIMESTAMP WHERE ID IN (SELECT ID FROM D)");q.addBindValue(id);q.addBindValue(archived);if(!q.exec())return fail(q.lastError().text());return {true,archived?"Branche archivée.":"Branche restaurée.",subtreeCodes(id),{}};}
ProductTreeResult ProductTreeService::removeNode(int id){QSqlDatabase db=QSqlDatabase::database(m_connectionName);QSqlQuery b(db);b.prepare("WITH RECURSIVE D(ID) AS(SELECT ? UNION ALL SELECT PT.ID FROM PT JOIN D ON PT.PARENT=D.ID) SELECT 'Exigence '||R.CODE FROM REQUIREMENT_PT X JOIN REQUIREMENT R ON R.ID=X.REQ_ID WHERE X.PT_ID IN D UNION SELECT 'Interface '||COALESCE(I.CODE,I.ID) FROM INTERFACE I WHERE I.ELEMENT1 IN D OR I.ELEMENT2 IN D UNION SELECT 'Changement '||C.CODE FROM CHANGE_LINK L JOIN CHANGE_ITEM C ON C.ID=L.CHANGE_ID WHERE L.OBJECT_TYPE='PT' AND L.OBJECT_ID IN D");b.addBindValue(id);b.exec();QStringList blockers;while(b.next())blockers<<b.value(0).toString();if(!blockers.isEmpty()){ProductTreeResult r=fail("La branche est utilisée et ne peut pas être supprimée.");r.blockers=blockers;return r;}QSqlQuery q(db);q.prepare("DELETE FROM PT WHERE ID=?");q.addBindValue(id);if(!q.exec())return fail(q.lastError().text());return {true,"Branche supprimée.",{}, {}};}
