#include "producttreewidget.h"
#include <QtWidgets>
#include <QSqlDatabase>
#include <QSqlQuery>
ProductTreeWidget::ProductTreeWidget(QWidget*p):QWidget(p){m_search=new QLineEdit;m_search->setPlaceholderText("Rechercher dans le product tree…");m_root=new QPushButton("Ajouter la racine");m_child=new QPushButton("Ajouter un enfant");m_remove=new QPushButton("Supprimer");m_archive=new QPushButton("Archiver / restaurer");m_showArchived=new QCheckBox("Afficher les archivés");auto tools=new QHBoxLayout;tools->addWidget(m_root);tools->addWidget(m_child);tools->addWidget(m_remove);tools->addWidget(m_archive);tools->addWidget(m_showArchived);tools->addStretch();tools->addWidget(m_search);m_tree=new QTreeWidget;m_tree->setHeaderLabels({"Code produit","Description"});m_tree->setSelectionMode(QAbstractItemView::SingleSelection);m_tree->setContextMenuPolicy(Qt::ActionsContextMenu);m_tree->addActions({new QAction("Ajouter un enfant",m_tree),new QAction("Supprimer",m_tree)});m_segment=new QLineEdit;m_code=new QLineEdit;m_code->setReadOnly(true);m_description=new QTextEdit;auto saveButton=new QPushButton("Enregistrer les propriétés");auto form=new QFormLayout;form->addRow("Segment local",m_segment);form->addRow("Code complet",m_code);form->addRow("Description",m_description);form->addRow(saveButton);m_links=new QTableWidget(0,2);m_links->setHorizontalHeaderLabels({"Objet lié","Référence"});m_links->horizontalHeader()->setSectionResizeMode(1,QHeaderView::Stretch);m_metrics=new QTableWidget(3,2);m_metrics->setVerticalHeaderLabels({"Exigences","Interfaces","Changements"});m_metrics->setHorizontalHeaderLabels({"Directs","Branche"});auto right=new QWidget;auto rv=new QVBoxLayout(right);rv->addLayout(form);rv->addWidget(new QLabel("Éléments liés"));rv->addWidget(m_links);rv->addWidget(new QLabel("Métriques"));rv->addWidget(m_metrics);auto split=new QSplitter;split->addWidget(m_tree);split->addWidget(right);split->setStretchFactor(0,1);split->setStretchFactor(1,1);QSettings s;s.beginGroup("ProductTree");split->restoreState(s.value("splitter").toByteArray());s.endGroup();connect(split,&QSplitter::splitterMoved,this,[split](int,int){QSettings s;s.setValue("ProductTree/splitter",split->saveState());});auto layout=new QVBoxLayout(this);layout->addLayout(tools);layout->addWidget(split);connect(m_tree,&QTreeWidget::currentItemChanged,this,[this](QTreeWidgetItem*c,QTreeWidgetItem*){selectNode(c);});connect(m_root,&QPushButton::clicked,this,&ProductTreeWidget::addRoot);connect(m_child,&QPushButton::clicked,this,&ProductTreeWidget::addChild);connect(m_remove,&QPushButton::clicked,this,&ProductTreeWidget::remove);connect(m_archive,&QPushButton::clicked,this,&ProductTreeWidget::archive);connect(saveButton,&QPushButton::clicked,this,&ProductTreeWidget::save);connect(m_search,&QLineEdit::textChanged,this,&ProductTreeWidget::filter);connect(m_showArchived,&QCheckBox::toggled,this,&ProductTreeWidget::refresh);}
void ProductTreeWidget::setConnectionName(const QString&n){m_connection=n;m_service.setConnectionName(n);refresh();}
QTreeWidgetItem* ProductTreeWidget::addItems(int parent,QTreeWidgetItem*pi){QSqlQuery q(QSqlDatabase::database(m_connection));q.prepare("SELECT ID,SEGMENT,DESCRIPTION,ARCHIVED FROM PT WHERE "+QString(parent<0?"PARENT IS NULL":"PARENT=?")+(m_showArchived->isChecked()?"":" AND ARCHIVED=0")+" ORDER BY POSITION,SEGMENT");if(parent>=0)q.addBindValue(parent);q.exec();QTreeWidgetItem*last=nullptr;while(q.next()){last=new QTreeWidgetItem({m_service.fullCode(q.value(0).toInt()),q.value(2).toString()});last->setData(0,Qt::UserRole,q.value(0));last->setData(0,Qt::UserRole+1,q.value(3));if(q.value(3).toBool())last->setForeground(0,QBrush(Qt::gray));pi?pi->addChild(last):m_tree->addTopLevelItem(last);addItems(q.value(0).toInt(),last);}return last;}
void ProductTreeWidget::refresh(){if(!QSqlDatabase::database(m_connection).isOpen())return;m_tree->clear();addItems(-1,nullptr);m_tree->expandAll();QSqlQuery q("SELECT COUNT(*) FROM PT WHERE PARENT IS NULL AND ARCHIVED=0",QSqlDatabase::database(m_connection));q.next();m_root->setEnabled(q.value(0).toInt()==0);}
int ProductTreeWidget::selectedId()const{return m_tree->currentItem()?m_tree->currentItem()->data(0,Qt::UserRole).toInt():-1;}
void ProductTreeWidget::addRoot(){bool ok;QString s=QInputDialog::getText(this,"Racine","Segment de la racine",QLineEdit::Normal,{},&ok);if(ok)showResult(m_service.addNode(-1,s));}
void ProductTreeWidget::addChild(){if(selectedId()<0)return;bool ok;QString s=QInputDialog::getText(this,"Nouvel élément","Segment local",QLineEdit::Normal,{},&ok);if(ok)showResult(m_service.addNode(selectedId(),s));}
void ProductTreeWidget::save(){if(selectedId()>=0)showResult(m_service.updateNode(selectedId(),m_segment->text(),m_description->toPlainText()));}
void ProductTreeWidget::remove(){if(selectedId()<0||QMessageBox::question(this,"Suppression","Supprimer cette branche inutilisée ?")!=QMessageBox::Yes)return;showResult(m_service.removeNode(selectedId()));}
void ProductTreeWidget::archive(){if(selectedId()>=0)showResult(m_service.setArchived(selectedId(),!m_tree->currentItem()->data(0,Qt::UserRole+1).toBool()));}
void ProductTreeWidget::showResult(const ProductTreeResult&r){if(!r.success)QMessageBox::warning(this,"Product tree",r.message+(r.blockers.isEmpty()?"":"\n\n"+r.blockers.join("\n")));else{refresh();emit dataChanged();}}
void ProductTreeWidget::filter(const QString&t){QList<QTreeWidgetItem*>all=m_tree->findItems("*",Qt::MatchWildcard|Qt::MatchRecursive);for(auto*i:all)i->setHidden(!t.isEmpty()&&!i->text(0).contains(t,Qt::CaseInsensitive)&&!i->text(1).contains(t,Qt::CaseInsensitive));}
void ProductTreeWidget::selectNode(QTreeWidgetItem*i){m_links->setRowCount(0);if(!i)return;int id=selectedId();QSqlQuery q(QSqlDatabase::database(m_connection));q.prepare("SELECT SEGMENT,DESCRIPTION,ARCHIVED FROM PT WHERE ID=?");q.addBindValue(id);q.exec();q.next();m_segment->setText(q.value(0).toString());m_description->setText(q.value(1).toString());m_code->setText(m_service.fullCode(id));QString subtree="WITH RECURSIVE D(ID) AS(SELECT "+QString::number(id)+" UNION ALL SELECT PT.ID FROM PT JOIN D ON PT.PARENT=D.ID) ";QStringList counts={"SELECT COUNT(*) FROM REQUIREMENT_PT WHERE PT_ID","SELECT COUNT(*) FROM INTERFACE WHERE ELEMENT1","SELECT COUNT(*) FROM CHANGE_LINK WHERE OBJECT_TYPE='PT' AND OBJECT_ID"};for(int r=0;r<3;r++){QSqlQuery a(counts[r]+"="+QString::number(id),QSqlDatabase::database(m_connection));a.next();m_metrics->setItem(r,0,new QTableWidgetItem(a.value(0).toString()));QSqlQuery b(subtree+counts[r]+" IN D",QSqlDatabase::database(m_connection));b.next();m_metrics->setItem(r,1,new QTableWidgetItem(b.value(0).toString()));}}
